name: Go

on: [ pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Go modules cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42
          args: --verbose

    - name: Build
      run: make k0sctl

    - name: Test
      run: make test

    - name: Cache the compiled binary for further testing
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: k0sctl
        retention-days: 5

    - name: Build all
      run: make build-all

  smoke-basic:
    strategy:
      matrix:
        image:
          - quay.io/footloose/ubuntu18.04
          - quay.io/footloose/centos7
          - quay.io/footloose/debian10
          - quay.io/footloose/fedora29
    name: Basic 1+1 smoke
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Restore the compiled binary for smoke testing
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: K0sctl cache
        uses: actions/cache@v2
        with:
          path: |
            /var/cache/k0sctl
            ~/.k0sctl/cache
            !*.log
          key: k0sctl-cache

      - name: Kubectl cache
        uses: actions/cache@v2
        with:
          path: |
            smoke-test/kubectl
          key: kubectl-1.21.3

      - name: Docker Layer Caching For Footloose
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Run smoke tests
        env:
          LINUX_IMAGE: ${{ matrix.image }}
        run: make -C smoke-test basic

  smoke-os-override:
    name: OS override smoke test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Restore the compiled binary for smoke testing
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: K0sctl cache
        uses: actions/cache@v2
        with:
          path: |
            /var/cache/k0sctl
            ~/.k0sctl/cache
            !*.log
          key: k0sctl-cache

      - name: Docker Layer Caching For Footloose
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Run OS override smoke test
        run: make -C smoke-test os-override

  smoke-upgrade:
    strategy:
      matrix:
        image:
          - quay.io/footloose/ubuntu18.04
          - quay.io/footloose/centos7
          #- quay.io/footloose/amazonlinux2
          #- quay.io/footloose/debian10
          #- quay.io/footloose/fedora29
    name: Upgrade 0.10 --> 0.11
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Restore the compiled binary for smoke testing
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: K0sctl cache
        uses: actions/cache@v2
        with:
          path: |
            /var/cache/k0sctl
            ~/.k0sctl/cache
            !*.log
          key: k0sctl-cache

      - name: Docker Layer Caching For Footloose
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Run smoke tests
        env:
          LINUX_IMAGE: ${{ matrix.image }}
        run: make -C smoke-test upgrade

  smoke-reset:
    strategy:
      matrix:
        image:
          - quay.io/footloose/ubuntu18.04
          - quay.io/footloose/centos7
    name: Apply + reset
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Restore the compiled binary for smoke testing
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: Run smoke tests
        env:
          LINUX_IMAGE: ${{ matrix.image }}
        run: make -C smoke-test reset

  smoke-backup-restore:
    strategy:
      matrix:
        image:
          - quay.io/footloose/ubuntu18.04
          - quay.io/footloose/centos7
    name: Apply + backup + reset + restore
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Restore the compiled binary for smoke testing
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: Run smoke tests
        env:
          LINUX_IMAGE: ${{ matrix.image }}
        run: make -C smoke-test backup-restore

  smoke-init:
    name: Init sub-command smoke test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Restore the compiled binary for smoke testing
        uses: actions/download-artifact@v2
        with:
          name: binary

      - name: K0sctl cache
        uses: actions/cache@v2
        with:
          path: |
            /var/cache/k0sctl
            ~/.k0sctl/cache
            !*.log
          key: k0sctl-cache

      - name: Docker Layer Caching For Footloose
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Run init smoke test
        run: make -C smoke-test init
